### ISSUE TITLE
Communication fails between pusher and back

### ISSUE THREAD

**Issue by fcecagno** [workadventure/workadventure#2336]
Hi,

Running 1.11.2, after a few days, communication fails between pusher and back, and after that, nobody could log in. This is the log on the pusher:

```
2022-06-21T11:57:42.497098163Z Could not find the GameRoom the user is leaving!
2022-06-21T11:57:42.497147906Z Connection error between pusher and back server Error: 14 UNAVAILABLE: TCP Read failed
2022-06-21T11:57:42.497177861Z     at Object.exports.createStatusError (/usr/src/node_modules/grpc/src/common.js:91:15)
2022-06-21T11:57:42.497240812Z     at ClientReadableStream._emitStatusIfDone (/usr/src/node_modules/grpc/src/client.js:233:26)
2022-06-21T11:57:42.497271046Z     at ClientReadableStream._receiveStatus (/usr/src/node_modules/grpc/src/client.js:211:8)
2022-06-21T11:57:42.497296349Z     at Object.onReceiveStatus (/usr/src/node_modules/grpc/src/client_interceptors.js:1277:15)
2022-06-21T11:57:42.497345664Z     at InterceptingListener._callNext (/usr/src/node_modules/grpc/src/client_interceptors.js:568:42)
2022-06-21T11:57:42.497391400Z     at InterceptingListener.onReceiveStatus (/usr/src/node_modules/grpc/src/client_interceptors.js:618:8)
2022-06-21T11:57:42.497453157Z     at /usr/src/node_modules/grpc/src/client_interceptors.js:1033:24 {
2022-06-21T11:57:42.497493392Z   code: 14,
2022-06-21T11:57:42.497548173Z   metadata: Metadata { _internal_repr: {}, flags: 0 },
2022-06-21T11:57:42.497591088Z   details: 'TCP Read failed'
2022-06-21T11:57:42.497646926Z }
2022-06-21T11:57:42.498204613Z Error in connection to back server 'back-ws:50051' for room 'https://xxx/map.json': Error: 14 UNAVAILABLE: TCP Read failed
2022-06-21T11:57:42.498302881Z     at Object.exports.createStatusError (/usr/src/node_modules/grpc/src/common.js:91:15)
2022-06-21T11:57:42.498336624Z     at ClientDuplexStream._emitStatusIfDone (/usr/src/node_modules/grpc/src/client.js:233:26)
2022-06-21T11:57:42.498413624Z     at ClientDuplexStream._receiveStatus (/usr/src/node_modules/grpc/src/client.js:211:8)
2022-06-21T11:57:42.498473431Z     at Object.onReceiveStatus (/usr/src/node_modules/grpc/src/client_interceptors.js:1311:15)
2022-06-21T11:57:42.498517486Z     at InterceptingListener._callNext (/usr/src/node_modules/grpc/src/client_interceptors.js:568:42)
2022-06-21T11:57:42.498559214Z     at InterceptingListener.onReceiveStatus (/usr/src/node_modules/grpc/src/client_interceptors.js:618:8)
2022-06-21T11:57:42.498609624Z     at /usr/src/node_modules/grpc/src/client_interceptors.js:1127:18 {
2022-06-21T11:57:42.498661580Z   code: 14,
2022-06-21T11:57:42.498696637Z   metadata: Metadata { _internal_repr: {}, flags: 0 },
2022-06-21T11:57:42.498747796Z   details: 'TCP Read failed'
2022-06-21T11:57:42.498783300Z }
```

It logged three times `Error in connection to back server` and then it just stopped trying.

**Comment by fcecagno** [comment]
It would be helpful to have a Prometheus metric for the connection status between pusher and back, so we have more visibility on this kind of issue.

**Comment by nolway** [comment]
Fix in the latest version.
