### ISSUE TITLE
Unable to run behind nginx reverse proxy

### ISSUE THREAD

**Issue by netzwerkgoettin** [workadventure/workadventure#3309]
Hi folks,

I'm running an older version of WA behind my `nginx` reverse proxy for several months now; can't determine the exact version, it was a master clone with a devel Docker setup. I'd like to have it more defined, so I got 1.15.12 release and try to get it up & running.

`nginx` handles all subdomains, certificate and headers. WA is running by Docker. I created `docker-compose.yml`: it's a copy of `contrib/docker/docker-compose.prod.yaml` without Let's Encrypt and `traefik.*-ssl` stuff.

### What's the actual error?
* when loading the WA site, it simply *hangs*
* the last messages in Developer Tools I see:
```
Socket has been opened
main.111d9723.js:14 Script started successfully
RoomConnection.ts:556 An error occurred server side: connect ECONNREFUSED 172.18.0.10:443
socket.onmessage @ RoomConnection.ts:556
RoomConnection.ts:284 An error occurred server side: connect ECONNREFUSED 172.18.0.10:443
socket.onmessage @ RoomConnection.ts:284
GameScene.ts:728 this.room Room
```

* `172.18.0.10` is the internal IP of `workadventure-11512-back-1`
```
docker ps |grep back
9a7393cdd359   thecodingmachine/workadventure-back:master          "docker-entrypoint.s…"   22 hours ago     Up 25 seconds         8080/tcp, 50051/tcp                                                                                         workadventure-11512-back-1
```

* and the back container logs DEBUG stuff like this:
```
workadventure-11512-back-1         | joinRoom called
workadventure-11512-back-1         | AxiosError: connect ECONNREFUSED 172.18.0.10:443
workadventure-11512-back-1         |     at Function.AxiosError.from (/usr/src/node_modules/axios/lib/core/AxiosError.js:89:14)
workadventure-11512-back-1         |     at RedirectableRequest.handleRequestError (/usr/src/node_modules/axios/lib/adapters/http.js:569:25)
workadventure-11512-back-1         |     at RedirectableRequest.emit (node:events:513:28)
workadventure-11512-back-1         |     at RedirectableRequest.emit (node:domain:489:12)
workadventure-11512-back-1         |     at ClientRequest.eventHandlers.<computed> (/usr/src/node_modules/follow-redirects/index.js:14:24)
workadventure-11512-back-1         |     at ClientRequest.emit (node:events:513:28)
workadventure-11512-back-1         |     at ClientRequest.emit (node:domain:489:12)
workadventure-11512-back-1         |     at TLSSocket.socketErrorListener (node:_http_client:494:9)
workadventure-11512-back-1         |     at TLSSocket.emit (node:events:513:28)
workadventure-11512-back-1         |     at TLSSocket.emit (node:domain:489:12) {
workadventure-11512-back-1         |   port: 443,
workadventure-11512-back-1         |   address: '172.18.0.10',
workadventure-11512-back-1         |   syscall: 'connect',
workadventure-11512-back-1         |   code: 'ECONNREFUSED',
workadventure-11512-back-1         |   errno: -111,
workadventure-11512-back-1         |   config: {
workadventure-11512-back-1         |     transitional: {
workadventure-11512-back-1         |       silentJSONParsing: true,
workadventure-11512-back-1         |       forcedJSONParsing: true,
workadventure-11512-back-1         |       clarifyTimeoutError: false
workadventure-11512-back-1         |     },
workadventure-11512-back-1         |     adapter: [ 'xhr', 'http' ],
workadventure-11512-back-1         |     transformRequest: [ [Function: transformRequest] ],
workadventure-11512-back-1         |     transformResponse: [ [Function: transformResponse] ],
workadventure-11512-back-1         |     timeout: 0,
workadventure-11512-back-1         |     xsrfCookieName: 'XSRF-TOKEN',
workadventure-11512-back-1         |     xsrfHeaderName: 'X-XSRF-TOKEN',
workadventure-11512-back-1         |     maxContentLength: -1,
workadventure-11512-back-1         |     maxBodyLength: -1,
workadventure-11512-back-1         |     env: { FormData: [Function], Blob: [class Blob] },
workadventure-11512-back-1         |     validateStatus: [Function: validateStatus],
workadventure-11512-back-1         |     headers: AxiosHeaders {
workadventure-11512-back-1         |       Accept: 'application/json, text/plain, */*',
workadventure-11512-back-1         |       Authorization: '',
workadventure-11512-back-1         |       'User-Agent': 'axios/1.3.2',
workadventure-11512-back-1         |       'Accept-Encoding': 'gzip, compress, deflate, br'
workadventure-11512-back-1         |     },
```

`back` is not listening on `443` at all, so `ECONNREFUSED` comes at no surprise. But I can't figure out where this hardcoded connection to `back:443` comes from.

So any suggestion on this would be highly appreciated.

Thanks a lot,
  Marianne

**Comment by moufmouf** [comment]
Hey Marianne,

The `AxiosError: connect ECONNREFUSED 172.18.0.10:443` error is the back making an outbound request to `172.18.0.10:443`.
The "back" makes Axios requests to fetch the map. So my guess is that the issue is with the container containing the maps. Try loading a map somewhere on Github to see if this works (like https://[your url]/_/global/workadventure.github.io/wa-internal-map/map.json )

**Comment by netzwerkgoettin** [comment]
Hi @moufmouf,

thanks a lot for your answer. Initially, it didn't help me a lot – as `172.18.0.10` in my case **is** the IPv4 for the `back` container. So `back` tried to make a connection to itself, and this error persisted when using the map stored on GitHub as you mentioned.

But I had some kind of epiphany 😎 I used `contrib/docker/.env.prod.template` as a starting point for my `.env`. The undocumented `ADMIN_API_URL` (at least I was not able to find usable information) is unset, as it is in the ~1 year old version I'm successfully running. I thought leaving it unset as it was would be okay, but in `1.15.12`, the `back` container refuses to start when unset.

```
workadventure-11512-back-1         | -----------------------------------------
workadventure-11512-back-1         | FATAL ERRORS FOUND IN ENVIRONMENT VARIABLES!!!
workadventure-11512-back-1         | -----------------------------------------
workadventure-11512-back-1         |
workadventure-11512-back-1         | For variable "ADMIN_API_URL": Invalid url
workadventure-11512-back-1         |
workadventure-11512-back-1         | -----------------------------------------
workadventure-11512-back-1         |
workadventure-11512-back-1         |
workadventure-11512-back-1         |
workadventure-11512-back-1         | npm ERR! Lifecycle script `runprod` failed with error:
workadventure-11512-back-1         | npm ERR! Error: command failed
workadventure-11512-back-1         | npm ERR!   in workspace: workadventureback@1.0.0
workadventure-11512-back-1         | npm ERR!   at location: /usr/src/back
workadventure-11512-back-1 exited with code 1
```

So I tried several settings, one of them was `ADMIN_API_URL=https://api.mydomain`, and that's what caused the *„hardcoded“* connection from `back` to itself on port 443.

`ADMIN_API_URL` must not be unset.
**But when commenting it, everything works as expected.**

```diff
## in file .env
# SAAS admin panel
- ADMIN_API_URL=
+ ##ADMIN_API_URL=
```

I love WorkAdventure (and my small community does, too) – but it is increasingly hard work to get it up & running. But I'll close this now as my issue is solved.

Thanks a lot and many regards,
  Marianne
