### ISSUE TITLE
Avoid Double Authentication with Authentik OIDC in WorkAdventure

### ISSUE THREAD

**Issue by dercaptainbc** [workadventure/workadventure#4450]
When using Authentik as the OIDC provider for WorkAdventure, users are required to authenticate twice if they are not already logged into Authentik. This creates a frustrating user experience, especially when OTP (One-Time Password) is used as part of two-factor authentication (2FA).

**Expected Behavior**
When opening WorkAdventure, a user should be redirected to Authentik only once to complete the authentication process (including 2FA). After successful authentication, the user should be logged into WorkAdventure without being prompted to authenticate again.

**Actual Behavior**
Users are required to log in twice in Authentik, including entering OTPs twice, before being granted access to WorkAdventure.

This issue introduces unnecessary delays and inconvenience for users, particularly when using OTP-based 2FA, as the second authentication often requires waiting for a new OTP to be generated.

**Environment Variables**
```
OPID_CLIENT_ID=client_id
OPID_CLIENT_SECRET=client_secret
OPID_CLIENT_ISSUER=https://authentik_url/application/o/workadventure/
OPID_PROFILE_SCREEN_PROVIDER=https://authentik_url/application/o/userinfo/
OPID_LOGOUT_REDIRECT_URL=https://authentik_url/application/o/workadventure/end-session/
OPID_USERNAME_CLAIM=preferred_username
OPID_LOCALE_CLAIM=locale
OPID_SCOPE=openid email
OPID_WOKA_NAME_POLICY=force_opid
```

**Comment by moufmouf** [comment]
Weird!
Question: are you using the [Matrix integration](https://github.com/workadventure/workadventure/blob/develop/docs/others/self-hosting/matrix.md) or not at all? If yes, does the problem disappear if you disable the Matrix integration?

**Comment by dercaptainbc** [comment]
Hi @moufmouf we dont use the matrix integration. I remember that the error also occurred in older versions, which is why we didn't have an OPID for workadventrue until now.

**Comment by moufmouf** [comment]
This is very very strange. Could you track what redirection are happening when you do the login flow?

Maybe a screenshot of the network tab on each page of the flow?
Or any way I could reproduce this?

**Comment by linjoe2** [comment]
Zitadel gives me exactly the same behaiviour, so @dercaptainbc is not the only person with this issue.

If I am already signed in to my oauth, it somehow will ask me to relogin, while if i open any other app that is connected to the oauth, it just instantly is logged in.

making screenshots of the network tab has not much sense, as it instantly redirects towards my oauth provider and therefore left workadventure.

setting up oauth should most likely cause this issue, otherwise i'd be happy to go on a video call and code through it together.

**Comment by moufmouf** [comment]
I'm wondering if this could not be related to the way different OpenID Connect providers handle the "prompt" parameter.

I think we use "prompt=login" by default but this can be configured with OPID_PROMPT env var.

https://www.cerberauth.com/blog/openid-connect-oauth2-prompts/

Could you try playing with this value? Maybe start with OPID_PROMPT=none

**Comment by dercaptainbc** [comment]
setting `OPID_PROMPT=none` (instead of login) results in the following error `“An error occurred while connecting to OpenID Provider”

extended by this error in the play container log
```
D 2024-12-17T06:28:30.040Z | load_balancing_call | [50] startRead called
An error occurred while connecting to OpenID Provider =>  OPError: login_required (The Authorization Server requires End-User authentication)
    at Client.callback (/usr/src/node_modules/openid-client/lib/client.js:426:13)
    at <anonymous> (/usr/src/play/src/pusher/services/OpenIDClient.ts:143:27)
    at Route.handler (/usr/src/play/src/pusher/controllers/AuthenticateController.ts:296:28)
    at async /usr/src/node_modules/hyper-express/src/components/router/Route.js:119:25 {
  error: 'login_required',
  error_description: 'The Authorization Server requires End-User authentication',
  state: 'a9f1f03f-8c0a-46fc-afcf-651451404a61'
}
```

**Comment by moufmouf** [comment]
Mmmmmm.... got it.

I thnk the issue comes from here: [EnvironmentVariable.ts](https://github.com/thecodingmachine/workadventure/blob/7d5debce2a7eeda087062c0aa91f2ef8d2e1ee78/play/src/pusher/enums/EnvironmentVariable.ts#L61-L61)

The "prompt" is forced to "login" if no value is set, but maybe it needs to be set to nothing.... Noyt sure what the impacts for the other users would be though.

**Comment by moufmouf** [comment]
Ok, I created a test image that allows to completely disable the "prompt" parameter. Could you try this?

https://hub.docker.com/layers/thecodingmachine/workadventure-play/opid_login_empty/images/sha256-1a357d1078a79ee506fd57c3a5d961ded65a0d9ab87b75840572019507b8bf05

- change the tag of the images to "opid_login_empty"
- Set OPID_PROMPT to an empty value

If this works, I'll consider merging the fix!

**Comment by dercaptainbc** [comment]
it seems to work for me with that version

**Comment by dercaptainbc** [comment]
Hi @moufmouf 
when will this be merged to the release branch?

**Comment by cofifield** [comment]
Just wanted to add, using the master image, OPID_PROMPT=undefined, and the changes proposed in #4493 fixed all of the issues we were having with Authentik.
